name: weatherapp_demo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  geolocator: ^12.0.0
  http: ^1.2.1
  geocoding: ^3.0.0
  firebase_core: ^4.0.0
  firebase_remote_config: ^6.0.0
  shared_preferences: ^2.2.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon_logo/wag.png"

flutter:
  uses-material-design: true
  assets:
    - assets/home/
    - assets/icon_logo/
    - assets/splash/
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/Rubik-VariableFont_wght.ttf